language: perl
dist: xenial
notifications:
  email:
    recipients:
    - kschwarz@hexonet.net
    on_success: never
    on_failure: always
perl:
  - "5.28"
  - "5.26"
install:
  - cpanm WebService::Hexonet::Connector --quiet --notest --sudo
script:
  # replace the below with unit tests one day
  - perl ./app_session.pl
  - perl ./app_nosession.pl
