name: Release
on: 
  # will run for every branch, except tags. See RSRMID-206.
  push:
    # Sequence of patterns matched against refs/heads
    branches:
      - "**"
    # Sequence of patterns matched against refs/tags
    tags-ignore: 
      - "**"
  pull_request:
    branches:
      - "**"
    tags-ignore: 
      - "**"

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Perl v${{ matrix.perl-version }}"
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.32"
          #- "5.30"

    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: cpanm --cpanfile="cpanfile" --installdeps .
        env:
          PERL_MM_USE_DEFAULT: 1
      - name: "run app"
        run: |
          perl ./app_session.pl
          perl ./app_nosession.pl
