name: Release
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Perl v${{ matrix.perl-version }}"

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.32"
          #- "5.30"

    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: |
          perl -V
          cpanm --local-lib=~/perl5 local::lib && eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib)
          cpanm http://www.cpan.org/authors/id/H/HE/HEXONET/WebService-Hexonet-Connector-v2.10.2.tar.gz
      - name: "run app"
        run: |
          perl ./app_session.pl
          perl ./app_nosession.pl
