name: Release
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    name: "Perl v${{ matrix.perl-version }}"

    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.32"
          #- "5.30"

    steps:
      - uses: actions/checkout@v2
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl }}
      - run: |
          perl -V
          cpanm --installdeps .
      - name: "run app"
        run: |
          perl ./app_session.pl
          perl ./app_nosession.pl
