name: Test
on: 
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    name:  🧪 Build & Test
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    strategy:
      fail-fast: false
      matrix:
        perl-version:
          - "5.32"
          #- "5.30"

    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: cpanm --cpanfile="cpanfile" --installdeps .
        env:
          PERL_MM_USE_DEFAULT: 1
      - name: run app
        run: |
          perl ./app_session.pl
          perl ./app_nosession.pl
