name: Test
on: 
  workflow_call:

jobs:
  test:
    if: github.event_name == 'pull_request' || (github.event_name == 'push' && github.actor != 'dependabot[bot]')
    name:  🧪 Build & Test
    runs-on: ${{ vars.RTLDEV_MW_CI_OS }}
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        perl-version: ${{ fromJson(vars.RTLDEV_MW_CI_PERL_MATRIX) }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up perl
        uses: shogo82148/actions-setup-perl@v1
        with:
          perl-version: ${{ matrix.perl-version }}
      - run: cpanm --cpanfile="cpanfile" --installdeps .
        env:
          PERL_MM_USE_DEFAULT: 1
      - name: run app
        run: |
          perl ./app_session.pl
          perl ./app_nosession.pl
